Drop table if exists tbl_user;

Create table tbl_user (
	user_id BIGINT PRIMARY key not NULL GENERATED BY DEFAULT AS IDENTITY,
  	user_name VARCHAR(45) NULL,
  	user_username VARCHAR(45) NULL,
  	user_password VARCHAR(45) NULL
	);
	

Create or replace FUNCTION sp_createUser(
	p_name VARCHAR(20),
    p_username VARCHAR(20),
    p_password VARCHAR(20)
) RETURNS text
as $$
	BEGIN
		if ( select exists (select 1 from tbl_user where user_username = p_username) ) THEN

			return 'Username Exists !!';

		ELSE

			insert into tbl_user
			(
				user_name,
				user_username,
				user_password
			)
			values
			(
				p_name,
				p_username,
				p_password
			);
			return 'User created successfully';
		END IF;
	END;
$$ LANGUAGE plpgsql;

Create or replace function sp_validateLogin(
	p_username VARCHAR(20)
as $$
		select * from tbl_user where user_username = p_username;
$$ LANGUAGE sql;
