Drop table if exists tbl_user cascade;

Create table tbl_user (
	user_id BIGINT PRIMARY key not NULL GENERATED BY DEFAULT AS IDENTITY,
  	user_name VARCHAR(45) NULL,
  	user_username VARCHAR(45) NULL,
  	user_password VARCHAR(45) NULL
	);
	
Drop table if exists tbl_company cascade;

Create table tbl_company (
	company_id BIGINT Primary key not null GENERATED BY DEFAULT AS IDENTITY,
	company_name VARCHAR(50), 
	date_of_founding DATE null constraint valid_date check (date_of_founding > '01-01-1900'::date), 
	country VARCHAR(50) null,
	revenue MONEY null,
	type_of_company VARCHAR(50) not null
	);
	
Drop table if exists tbl_launch cascade;

Create table tbl_launch (
	launch_id BIGINT Primary key not null GENERATED BY DEFAULT AS IDENTITY,
	date_of_launch DATE null constraint valid_date check (date_of_launch >= '04-10-1957'::date), 
	rocket VARCHAR(50) null,
	payload TEXT null,
	launch_company_id BIGINT,
	Foreign key (launch_company_id) references tbl_company (company_id) 
	);

Drop table if exists tbl_spacecraft cascade;
	
Create table tbl_spacecraft (
	spacecraft_id BIGINT Primary key not null GENERATED BY DEFAULT AS IDENTITY,
	sc_height INT null constraint valid_height check (sc_height > 0),
	sc_width INT null constraint valid_width check (sc_width > 0),
	sc_length INT null constraint valid_length check (sc_length > 0),
	construction_cost MONEY null,
	sc_name VARCHAR(50) null,
	design_cost MONEY null,
	manufacturer_company_id BIGINT,
	Foreign key (manufacturer_company_id) references tbl_company (company_id),
	produjction_site VARCHAR(50) null default 'Moscow, Russia',
	engine_type VARCHAR(50) null
	);
	
Drop table if exists tbl_NEObject cascade;
	
Create table tbl_NEObject (
	neo_vehicle_id BIGINT not null GENERATED BY DEFAULT AS IDENTITY,
	spacecraft_id BIGINT,
	Foreign key (spacecraft_id) references tbl_spacecraft (spacecraft_id),
	type_of_mission VARCHAR(50) not null, 
	orbit_type VARCHAR(50) null,
	altitude INT null constraint valid_altitude check (altitude > 200),
	speed REAL null constraint valid_speed check (speed >= 7.91),
	Primary key (neo_vehicle_id, spacecraft_id)
	);
	
Drop table if exists tbl_transport cascade;
	
Create table tbl_transport (
	transport_vehicle_id BIGINT not null GENERATED BY DEFAULT AS IDENTITY,
	spacecraft_id BIGINT,
	Foreign key (spacecraft_id) references tbl_spacecraft (spacecraft_id),
	cargo_volume INT null constraint valid_cargo_volume check(cargo_volume > 0),
	speed REAL null,
	type_of_cargo TEXT null,
	Primary key (transport_vehicle_id, spacecraft_id)
	);
	
Drop table if exists tbl_mining cascade;
	
Create table tbl_mining (
	mining_vehicle_id BIGINT not null GENERATED BY DEFAULT AS IDENTITY,
	spacecraft_id BIGINT,
	Foreign key (spacecraft_id) references tbl_spacecraft (spacecraft_id),
	production_rate INT null constraint valid_production_rate check(production_rate > 0),
	mining_material VARCHAR(50) null,
	start_of_service DATE not null,
	planned_end_of_service DATE not null,  
	Primary key (mining_vehicle_id, spacecraft_id)
	);
	
Drop table if exists tbl_research cascade;
	
Create table tbl_research (
	research_vehicle_id BIGINT not null GENERATED BY DEFAULT AS IDENTITY,
	spacecraft_id BIGINT,
	Foreign key (spacecraft_id) references tbl_spacecraft (spacecraft_id),
	object_of_study VARCHAR(50) not null,
	instruments_onboard TEXT null,
	start_of_service DATE not null,
	Primary key (research_vehicle_id, spacecraft_id)
	);
	
	
	
	
	
	